backend:
  name: "github"
  repo: "elizabethandjane/slideshows.elizabethandjane.ca"
  branch: "main"

site_url: "https://slideshows.elizabethandjane.ca/"
media_folder: "images/uploads"

collections:
  - name: "slideshows"
    label: "Slideshows"
    label_singular: "Slideshow"
    folder: "_posts"
    create: true
    slug: "{{fields.shoot_date}}-{{fields.slug}}"
    preview_path: "{{fields.category}}/{{year}}/{{fields.slug}}"
    preview_path_date_field: "shoot_date"
    summary: "{{fields.title}} — {{fields.category}} — {{fields.shoot_date}}"
    sortable_fields:
      - "title"
      - "shoot_date"
      - "category"
    view_filters:
      - label: "Weddings"
        field: "category"
        pattern: "weddings"
      - label: "Engagements"
        field: "category"
        pattern: "engagements"
      - label: "Portraits"
        field: "category"
        pattern: "portraits"
      - label: "Pets"
        field: "category"
        pattern: "pets"
      - label: "Newborn"
        field: "category"
        pattern: "newborn"
      - label: "Maternity"
        field: "category"
        pattern: "maternity"
    fields:
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - label: "Weddings"
            value: "weddings"
          - label: "Engagements"
            value: "engagements"
          - label: "Portraits"
            value: "portraits"
          - label: "Pets"
            value: "pets"
          - label: "Newborn"
            value: "newborn"
          - label: "Maternity"
            value: "maternity"
      - label: "Slug"
        name: "slug"
        width: "string"
        pattern:
          - "[a-z\\-]+"
          - "All lowercase, words separated with dashes."
        comment: "All lowercase, words separated with dashes."
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Shoot date"
        name: "shoot_date"
        widget: "date"
      - label: "Total photos"
        name: "total_photos"
        widget: "number"
      - label: "Music"
        name: "music"
        widget: "string"
